[can]
interface = "can0"

[web]
port = 8080
listen = "0.0.0.0"
static_path = "/usr/share/caniot-controller/ui/"
prometheus_metrics = true

[grpc]
listen = "0.0.0.0:50051"

[database]
# connection_string = "postgres://caniot:caniot@localhost/caniot"
connection_string = "sqlite:///var/lib/caniot-controller/caniot.db"
retry_interval = 1
retries = 0

[caniot]
pending_queries_default_timeout = 1000 # ms
action_default_timeout = 1000          # ms
inernal_api_mpsc_size = 20             # ms

[caniot.devices]
heaters_did = 1
garage_did = 16
outdoor_alarm_did = 24

[ui]
message = "Bienvenue sur votre contrôleur Caniot !"

[[ui.shortcut]]
name = "Grafana"
url = "/grafana"
icon = "grafana"
menu_order = "before_settings"
order = 10
target_blank = false
badge = true
badge_color = "red"

[[ui.shortcut]]
name = "Prometheus"
url = "/prometheus"
icon = "prometheus"
menu_order = "before_settings"
order = 11
target_blank = false
badge = true
badge_color = "red"

[[ui.shortcut]]
name = "swupdate"
url = "/swupdate"
icon = "swupdate"
menu_order = "end"
order = 90
target_blank = false
badge = true
badge_color = "blue"

[[ui.shortcut]]
name = "Home Assistant"
url = "http://ha.local.lan/"
icon = "homeassistant"
menu_order = "after_home"
order = 2
target_blank = true
badge = true
badge_color = "red"

[ha]

[copro]
listen_ip = "192.0.3.1"
listen_port = 4000

[[copro.devices]]
name = "Salon"
mac = "a4:c1:38:68:05:63"
ui_display_order = 1

[[copro.devices]]
name = "Chambre"
mac = "a4:c1:38:8d:ba:b4"
ui_display_order = 2

[[copro.devices]]
name = "Chambre Lucas"
mac = "a4:c1:38:ec:1c:6d"
ui_display_order = 3

[[copro.devices]]
name = "Bureau Papa"
mac = "a4:c1:38:3c:d3:21"
ui_display_order = 7

[[copro.devices]]
name = "Chambre Marie"
mac = "a4:c1:38:a7:30:c4"
ui_display_order = 4

[[copro.devices]]
name = "Salle de bain RDC"
mac = "a4:c1:38:28:17:e3"
ui_display_order = 5

[[copro.devices]]
name = "Bureau Maman"
mac = "a4:c1:38:56:5e:ce"
ui_display_order = 8

[[copro.devices]]
name = "Rangement"
mac = "a4:c1:38:0a:1e:38"
ui_display_order = 10

[[copro.devices]]
name = "Salle de bain étage"
mac = "a4:c1:38:d5:08:40"
ui_display_order = 6

[[copro.devices]]
name = "Mobile"
mac = "a4:c1:38:af:54:26"
ui_display_order = 11
