SUMMARY = "CANIOT Rust Controller"
HOMEPAGE = "https://github.com/lucasdietrich/caniot-rust-controller.git"
LICENSE = "CLOSED"

# Auto-Generated by cargo-bitbake 0.3.16
#
inherit cargo
inherit cargo-update-recipe-crates

# If this is git based prefer versioned ones if they exist
# DEFAULT_PREFERENCE = "-1"

# how to get caniot-controller could be as easy as but default to a git checkout:
SRC_BRANCH ?= "develop"
SRC_URI += "git://github.com/lucasdietrich/caniot-rust-controller.git;protocol=https;nobranch=1;branch=${SRC_BRANCH}"
SRCREV = "b07961e54e899b5dd580f6fd54202a5b7c77e5bd"
S = "${WORKDIR}/git"

CARGO_SRC_DIR = ""

SRC_URI += "git://github.com/lucasdietrich/zephyr-linux-ble-copro.git;protocol=https;nobranch=1;name=ble-copro-stream-server;destsuffix=ble-copro-stream-server;subpath=ble-copro-stream-server-rs \
            "

SRCREV_FORMAT .= "_ble-copro-stream-server"
SRCREV_ble-copro-stream-server = "883b2704578d9214571ac23c5ae348aeb82955c0"

# FIXME: update generateme with the real MD5 of the license file
LIC_FILES_CHKSUM = " \
    "

include caniot-controller-crates.inc

DEPENDS += "protobuf-native nodejs-native bash-native sqlite3-native"

inherit update-rc.d

# required by libsqlite3 to link against
inherit pkgconfig

FILESEXTRAPATHS:append := "${THISDIR}/files:"

SRC_URI += "file://caniot-controller.toml \
            file://caniot-controller.init \
            "

INITSCRIPT_NAME = "${PN}.init"
INITSCRIPT_PARAMS = "defaults 80"

PACKAGECONFIG ??= "sqlite3 ble-copro"
PACKAGECONFIG[sqlite3] = ",,sqlite3,"
PACKAGECONFIG[ble-copro] = ",,,ble-copro-usb-net"

do_compile[network] = "1"
do_compile:prepend() {
    # make sure a local npm cache is used (instead of the global one)
    OPTIONS="--prefer-online --cache ${WORKDIR}/npm-cache"

    cd ${S}/proto/grpc-web
    npm install ${OPTIONS}
    bash ./proto-gen-grpc-web.sh

    cd ${S}/ui
    npm install ${OPTIONS}
    npm run build ${OPTIONS}

    export LIBSQLITE3_SYS_USE_PKG_CONFIG=1
}

do_install:append() {
    # copy ui files
    install -d ${D}${datadir}/caniot-controller/ui
    cp -r ${S}/ui/dist/* ${D}${datadir}/caniot-controller/ui

    # copy configuration file
    install -d ${D}${sysconfdir}/caniot-controller
    install -m 0644 ${WORKDIR}/caniot-controller.toml ${D}${sysconfdir}/caniot-controller

    # copy init script
    install -d ${D}${sysconfdir}/init.d
    install -m 0755 ${WORKDIR}/caniot-controller.init ${D}${sysconfdir}/init.d/

    # prepare persitent data directory /var/lib/caniot-controller
    install -d ${D}${localstatedir}/lib/caniot-controller
}