{
 "title": "Linky TIC",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Puissance",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "device_power", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Courant",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "device_current", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Index d'energie",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "device_energy", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nombre de trames de mesures reçus",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "device_stats_rx{name=\"Linky TIC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RSSI moyen",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "device_rssi{name=\"Linky TIC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Puissance apparente (papp)",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "device_power", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Index d'énergie",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expr": "device_energy", "legendFormat": "__auto" }
   ]
  }
 ]
}